### ISSUE TITLE
No "timm-seresnet152d_320"

### ISSUE THREAD

**Issue by alckasoc** [dungnb1333/SIIM-COVID19-Detection#2]
I was looking at the classification_aux folder and I was trying to call the get_encoder() function from the SMP library with the encoder_name = "timm-seresnet152d_320". However, I got an error saying that this wasn't part of the supported model encoders. The closest one was a "seresnet152". Below is the code and error I got. Could this be a version problem? Thanks!
`se_resnet152d = get_encoder('timm-seresnet152d_320', 
                                   in_channels=3, depth=5,
                                   weights='imagenet')`
![image](https://user-images.githubusercontent.com/58043265/130423110-4acbceab-60ef-4536-a08e-dac29017ed1e.png)

**Comment by alckasoc** [comment]
Nevermind, I found the problem. There's a difference in versions.

**Comment by dungnb1333** [comment]
use src/classification_aux/segmentation_models_pytorch instead of https://github.com/qubvel/segmentation_models.pytorch, the default repo does not have seresnet152
